# Generated by Django 3.1.6 on 2021-03-13 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_event_type', models.CharField(max_length=200)),
                ('event_stamp', models.DateTimeField(default=datetime.datetime(2021, 3, 13, 20, 4, 26, 566222))),
                ('user_related_event', models.CharField(max_length=200)),
                ('ip_source', models.CharField(max_length=16)),
                ('user_browser', models.CharField(max_length=200)),
                ('user_os', models.CharField(max_length=200)),
                ('user_agent', models.CharField(max_length=200)),
            ],
        ),
    ]
