# Generated by Django 3.1.6 on 2021-03-13 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passevents',
            name='event_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 20, 4, 37, 685412)),
        ),
    ]
