# Generated by Django 3.1.6 on 2021-03-13 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210313_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='passevents',
            name='user_reset_reason',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='passevents',
            name='event_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 20, 12, 2, 863127)),
        ),
    ]
