# Generated by Django 3.1.7 on 2021-03-14 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210313_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passevents',
            name='event_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 17, 52, 38, 304315)),
        ),
    ]
