# Generated by Django 3.1.7 on 2021-03-14 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210314_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passevents',
            name='event_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 17, 55, 43, 59584)),
        ),
        migrations.AlterField(
            model_name='passevents',
            name='user_reset_reason',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
