# Generated by Django 3.1.7 on 2021-03-14 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210314_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passevents',
            name='event_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 17, 57, 37, 361046)),
        ),
        migrations.AlterField(
            model_name='passevents',
            name='user_reset_reason',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
